<#
.SYNOPSIS
Regenerates .cargo/config.toml with correct MSVC/Windows SDK include & lib paths.

.DESCRIPTION
Auto-detects the latest installed MSVC toolset under Visual Studio 2022 or 2026
and the latest installed Windows 10 SDK on disk, then writes a workspace-local
.cargo/config.toml so `cargo build` works from any shell or IDE without needing
to launch a Developer PowerShell first.

Run once, or rerun after installing/removing Visual Studio components.
#>
[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$cargoDir = Join-Path $repoRoot ".cargo"
$configPath = Join-Path $cargoDir "config.toml"

function Find-MsvcRoot {
    $candidates = @(
        "C:\Program Files\Microsoft Visual Studio\2022\*\VC\Tools\MSVC",
        "C:\Program Files\Microsoft Visual Studio\2022\*\VC\Tools\MSVC",
        "C:\Program Files\Microsoft Visual Studio\18\*\VC\Tools\MSVC",
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\*\VC\Tools\MSVC"
    )
    foreach ($pattern in $candidates) {
        $roots = Get-ChildItem -Path $pattern -Directory -ErrorAction SilentlyContinue
        foreach ($root in $roots) {
            $versions = Get-ChildItem -Path $root.FullName -Directory -ErrorAction SilentlyContinue |
                Where-Object { Test-Path (Join-Path $_.FullName "bin\HostX64\x64\cl.exe") } |
                Sort-Object { [version]$_.Name } -Descending
            if ($versions) {
                return $versions[0].FullName
            }
        }
    }
    throw "No MSVC toolset found. Install Visual Studio Build Tools with the 'Desktop development with C++' workload."
}

function Find-WindowsSdk {
    $kit = "C:\Program Files (x86)\Windows Kits\10"
    if (-not (Test-Path (Join-Path $kit "Include"))) {
        throw "Windows Kits 10 not found at $kit"
    }
    $versions = Get-ChildItem -Path (Join-Path $kit "Include") -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -match '^\d+\.\d+\.\d+\.\d+$' -and (Test-Path (Join-Path $_.FullName "ucrt\stddef.h")) } |
        Sort-Object { [version]$_.Name } -Descending
    if (-not $versions) {
        throw "No usable Windows 10 SDK (with ucrt\stddef.h) found under $kit\Include"
    }
    return [pscustomobject]@{
        Root    = $kit
        Version = $versions[0].Name
    }
}

$msvc = Find-MsvcRoot
$sdk  = Find-WindowsSdk
$kit  = $sdk.Root
$ver  = $sdk.Version

Write-Host "MSVC:        $msvc"
Write-Host "Windows SDK: $kit ($ver)"

$include = @(
    "$msvc\include",
    "$kit\Include\$ver\ucrt",
    "$kit\Include\$ver\shared",
    "$kit\Include\$ver\um",
    "$kit\Include\$ver\winrt",
    "$kit\Include\$ver\cppwinrt"
) -join ";"

$lib = @(
    "$msvc\lib\x64",
    "$kit\Lib\$ver\ucrt\x64",
    "$kit\Lib\$ver\um\x64"
) -join ";"

$includeToml = $include.Replace("\", "\\")
$libToml     = $lib.Replace("\", "\\")

$body = @"
# Auto-generated by scripts/setup-windows-env.ps1. Do not commit (machine-specific).
# Rerun the script after updating Visual Studio or the Windows SDK.

[env]
INCLUDE = "$includeToml"
LIB = "$libToml"
"@

New-Item -ItemType Directory -Force -Path $cargoDir | Out-Null
Set-Content -Path $configPath -Value $body -Encoding UTF8

Write-Host ""
Write-Host "Wrote $configPath"
Write-Host "Now run `cargo build` from any shell or IDE."
